# Generated by Django 6.0.3 on 2026-03-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='important_notes',
            field=models.TextField(blank=True, default='• Disable antivirus before extracting\n• Run as administrator\n• Install Visual C++ Redistributable if needed'),
        ),
        migrations.AddField(
            model_name='game',
            name='install_guide',
            field=models.TextField(blank=True, default='1. Extract the downloaded archive\n2. Run the game executable\n3. Enjoy!'),
        ),
        migrations.AddField(
            model_name='game',
            name='min_cpu',
            field=models.CharField(blank=True, default='Intel Core i5', max_length=200),
        ),
        migrations.AddField(
            model_name='game',
            name='min_gpu',
            field=models.CharField(blank=True, default='NVIDIA GTX 970', max_length=200),
        ),
        migrations.AddField(
            model_name='game',
            name='min_os',
            field=models.CharField(blank=True, default='Windows 10 64-bit', max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='min_ram',
            field=models.CharField(blank=True, default='8 GB RAM', max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='min_storage',
            field=models.CharField(blank=True, default='50 GB', max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='rec_cpu',
            field=models.CharField(blank=True, default='Intel Core i7', max_length=200),
        ),
        migrations.AddField(
            model_name='game',
            name='rec_gpu',
            field=models.CharField(blank=True, default='NVIDIA RTX 2070', max_length=200),
        ),
        migrations.AddField(
            model_name='game',
            name='rec_os',
            field=models.CharField(blank=True, default='Windows 11 64-bit', max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='rec_ram',
            field=models.CharField(blank=True, default='16 GB RAM', max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='rec_storage',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
