# Generated by Django 6.0.3 on 2026-03-14 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_important_notes_game_install_guide_game_min_cpu_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_title', models.CharField(max_length=200)),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('added', 'Added'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('votes', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-votes', '-created_at'],
            },
        ),
    ]
